(()=>{'use strict';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let client,timer,mode='all',sort='az',minDebt=0,cache=[],overdue=new Set(),applying=false;
function db(){if(!client&&window.supabase&&window.TEM_AQUI_SUPABASE){const c=window.TEM_AQUI_SUPABASE;client=window.supabase.createClient(c.url,c.publishableKey||c.anonKey)}return client}
function sid(){return localStorage.getItem('tag-pref-store')||document.getElementById('centralStoreSelect')?.value||''}
async function load(){const id=sid();if(!id||!db())return[];const [{data,error},{data:late,error:lateErr}]=await Promise.all([db().rpc('gestao_list_customers',{p_store_id:id,p_search:null}),db().from('store_customer_credit_movements').select('customer_id,due_date,movement_type').eq('store_id',id).eq('movement_type','purchase').lt('due_date',new Date().toISOString().slice(0,10))]);if(error)throw error;cache=data||[];overdue=lateErr?new Set():new Set((late||[]).map(x=>String(x.customer_id)));return cache}
function tabs(){const head=document.querySelector('[data-view="customers"] .page-heading');if(!head)return null;let t=document.getElementById('customerFichaTabs');if(!t){head.insertAdjacentHTML('afterend','<div id="customerFichaTabs" class="customer-ficha-tabs"><button data-cft="all" class="active">Clientes</button><button data-cft="open">Fichas em aberto</button><button data-cft="overdue">Vencidos</button><button data-cft="ranking">Ranking de clientes</button></div>');t=document.getElementById('customerFichaTabs')}return t}
function summary(){const t=tabs();if(!t)return;let s=document.getElementById('customerReceivableSummary');if(!s){t.insertAdjacentHTML('afterend','<div id="customerReceivableSummary" class="customer-receivable-summary"><div><span>Total a receber</span><strong id="customerReceivableTotal">R$ 0,00</strong></div><div><span>Fichas em aberto</span><strong id="customerReceivableCount">0</strong></div><div><span>Vencidas</span><strong id="customerOverdueCount">0</strong></div></div>');s=document.getElementById('customerReceivableSummary')}const total=cache.reduce((a,c)=>a+Math.max(0,Number(c.current_debt||0)),0),open=cache.filter(c=>Number(c.current_debt||0)>0).length,late=cache.filter(c=>Number(c.current_debt||0)>0&&overdue.has(String(c.id))).length;document.getElementById('customerReceivableTotal').textContent=money(total);document.getElementById('customerReceivableCount').textContent=String(open);document.getElementById('customerOverdueCount').textContent=String(late)}
function controls(){const card=document.querySelector('[data-view="customers"] .customer-list-card'),search=card?.querySelector('.inline-search');if(!card||!search)return;let c=document.getElementById('customerListTools');if(!c){search.insertAdjacentHTML('afterend','<div id="customerListTools" class="customer-list-tools"><label>Ordenar<select id="customerDebtSort"><option value="az">Nome A–Z</option><option value="debt_desc">Maior débito</option><option value="debt_asc">Menor débito</option></select></label><label>Débito mínimo<input id="customerDebtMin" type="number" min="0" step="0.01" placeholder="R$ 0,00"></label><div id="customerModeLabel" class="customer-mode-label"></div></div>')} }
function label(){const l=document.getElementById('customerModeLabel');if(!l)return;const names={all:'Todos os clientes',open:'Somente fichas em aberto',overdue:'Somente contas vencidas'};const n=visibleCustomers().length;l.textContent=`${names[mode]||''} · ${n} ${n===1?'cliente':'clientes'}`}
function visibleCustomers(){return cache.filter(c=>{const debt=Number(c.current_debt||0);if(debt<minDebt)return false;if(mode==='open'&&debt<=0)return false;if(mode==='overdue'&&!(debt>0&&overdue.has(String(c.id))))return false;return true})}
function cmp(a,b){if(sort==='debt_desc')return Number(b.current_debt||0)-Number(a.current_debt||0)||String(a.customer_name||'').localeCompare(String(b.customer_name||''),'pt-BR');if(sort==='debt_asc')return Number(a.current_debt||0)-Number(b.current_debt||0)||String(a.customer_name||'').localeCompare(String(b.customer_name||''),'pt-BR');return String(a.customer_name||'').localeCompare(String(b.customer_name||''),'pt-BR')}
function syncRows(){const list=document.getElementById('customerList');if(!list)return;const map=new Map(cache.map(c=>[String(c.id),c]));[...list.querySelectorAll('.customer-row')].forEach(r=>{const c=map.get(String(r.dataset.customerId));if(!c)return;const debt=Number(c.current_debt||0),b=r.querySelector(':scope > b');r.dataset.realDebt=String(debt);r.dataset.realName=String(c.customer_name||'');if(b){b.textContent=money(debt);b.dataset.label='Débito atual'}});const wanted=visibleCustomers().sort(cmp),rows=new Map([...list.querySelectorAll('.customer-row')].map(r=>[String(r.dataset.customerId),r]));[...rows.values()].forEach(r=>r.hidden=true);wanted.forEach(c=>{const r=rows.get(String(c.id));if(r){r.hidden=false;list.appendChild(r)}});label()}
async function ranking(){const detail=document.getElementById('customerDetail');if(!detail)return;const {data,error}=await db().rpc('gestao_customer_ranking',{p_store_id:sid()});if(error)throw error;detail.innerHTML=`<div class="ranking-head"><span>RANKING</span><h2>Clientes que mais compram</h2><p>Classificação pelo total comprado.</p></div><div class="ranking-list">${(data||[]).map((x,i)=>`<button class="ranking-row" data-rank-customer="${x.customer_id}"><b>${i+1}º</b><span><strong>${String(x.customer_name||'')}</strong><small>${Number(x.purchase_count||0)} compras · débito atual ${money(x.current_debt)}</small></span><em>${money(x.total_purchased)}</em></button>`).join('')||'<div class="empty-state">Ainda não há compras para montar o ranking.</div>'}</div>`}
function resetDetail(){const d=document.getElementById('customerDetail');if(d)d.innerHTML='<div class="empty-state">Selecione um cliente para abrir a ficha.</div>'}
async function apply(){if(applying)return;applying=true;try{tabs();controls();await load();summary();const layout=document.querySelector('[data-view="customers"] .customers-layout');document.querySelectorAll('[data-cft]').forEach(b=>b.classList.toggle('active',b.dataset.cft===mode));if(mode==='ranking'){layout?.classList.add('ranking-mode');await ranking()}else{layout?.classList.remove('ranking-mode');syncRows();if(document.querySelector('#customerDetail .ranking-head'))resetDetail()}}finally{applying=false}}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(()=>apply().catch(console.warn),ms)}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-cft]');if(tab){e.preventDefault();e.stopPropagation();mode=tab.dataset.cft;schedule(0);return}const r=e.target.closest('[data-rank-customer]');if(r){mode='all';schedule(0);setTimeout(()=>document.querySelector(`#customerList [data-customer-id="${r.dataset.rankCustomer}"]`)?.click(),180)}} ,true);
document.addEventListener('change',e=>{if(e.target?.id==='customerDebtSort'){sort=e.target.value;schedule(0)}});document.addEventListener('input',e=>{if(e.target?.id==='customerDebtMin'){minDebt=Math.max(0,Number(e.target.value||0));schedule(40)}});document.addEventListener('click',e=>{if(e.target?.id==='saveCreditEntry'||e.target?.closest('[data-receive-payment]'))setTimeout(()=>schedule(0),450)});
window.addEventListener('load',()=>{tabs();controls();const list=document.getElementById('customerList');if(list)new MutationObserver(()=>{if(!applying)schedule(100)}).observe(list,{childList:true});schedule(20)});
})();