(()=>{'use strict';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let client,timer;
function db(){if(!client&&window.supabase&&window.TEM_AQUI_SUPABASE){const c=window.TEM_AQUI_SUPABASE;client=window.supabase.createClient(c.url,c.publishableKey||c.anonKey)}return client}
function storeId(){return localStorage.getItem('tag-pref-store')||document.getElementById('centralStoreSelect')?.value||''}
async function customers(){const sid=storeId();if(!sid||!db())return[];const {data,error}=await db().rpc('gestao_list_customers',{p_store_id:sid,p_search:null});if(error)throw error;return data||[]}
function ensureControls(){const card=document.querySelector('[data-view="customers"] .customer-list-card');if(!card)return;const search=card.querySelector('.inline-search');if(!document.getElementById('customerDebtOverview')&&search)search.insertAdjacentHTML('afterend','<div id="customerDebtOverview" class="customer-debt-overview"><div><span>Total a receber</span><strong id="customerDebtTotal">R$ 0,00</strong><small id="customerDebtCount">0 fichas em aberto</small></div><label>Ordenar<select id="customerDebtSort"><option value="az">Nome A–Z</option><option value="debt_desc">Maior débito</option><option value="debt_asc">Menor débito</option></select></label><label>Débito mínimo<input id="customerDebtMin" type="number" min="0" step="0.01" placeholder="R$ 0,00"></label></div>')}
async function apply(){const list=document.getElementById('customerList');if(!list)return;ensureControls();const cs=await customers(),map=new Map(cs.map(c=>[String(c.id),c]));const total=cs.reduce((s,c)=>s+Math.max(0,Number(c.current_debt||0)),0),count=cs.filter(c=>Number(c.current_debt||0)>0).length;if(document.getElementById('customerDebtTotal'))document.getElementById('customerDebtTotal').textContent=money(total);if(document.getElementById('customerDebtCount'))document.getElementById('customerDebtCount').textContent=`${count} ${count===1?'ficha em aberto':'fichas em aberto'}`;const sort=document.getElementById('customerDebtSort')?.value||'az',min=Math.max(0,Number(document.getElementById('customerDebtMin')?.value||0));let rows=[...list.querySelectorAll('.customer-row')];rows.forEach(r=>{const c=map.get(String(r.dataset.customerId));if(!c)return;const debt=Number(c.current_debt||0),b=r.querySelector(':scope > b');r.dataset.realDebt=String(debt);r.dataset.realName=String(c.customer_name||'');if(b){b.textContent=money(debt);b.dataset.label='Débito atual'}if(min>0)r.hidden=debt<min});rows=rows.filter(r=>!r.hidden);rows.sort((a,b)=>{const da=Number(a.dataset.realDebt||0),dbb=Number(b.dataset.realDebt||0),na=a.dataset.realName||'',nb=b.dataset.realName||'';if(sort==='debt_desc')return dbb-da||na.localeCompare(nb,'pt-BR');if(sort==='debt_asc')return da-dbb||na.localeCompare(nb,'pt-BR');return na.localeCompare(nb,'pt-BR')});rows.forEach(r=>list.appendChild(r))}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>apply().catch(console.warn),260)}
document.addEventListener('change',e=>{if(e.target?.id==='customerDebtSort')schedule()});document.addEventListener('input',e=>{if(e.target?.id==='customerDebtMin')schedule()});document.addEventListener('click',e=>{if(e.target?.id==='saveCreditEntry')setTimeout(()=>{const active=document.querySelector('#customerList .customer-row.active');active?.click();schedule()},850)});
window.addEventListener('load',()=>{const root=document.querySelector('[data-view="customers"]');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});schedule()});
})();