(()=>{'use strict';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let client,timer,applying=false,lastSignature='';
function db(){if(!client&&window.supabase&&window.TEM_AQUI_SUPABASE){const c=window.TEM_AQUI_SUPABASE;client=window.supabase.createClient(c.url,c.publishableKey||c.anonKey)}return client}
function storeId(){return localStorage.getItem('tag-pref-store')||document.getElementById('centralStoreSelect')?.value||''}
async function customers(){const sid=storeId();if(!sid||!db())return[];const {data,error}=await db().rpc('gestao_list_customers',{p_store_id:sid,p_search:null});if(error)throw error;return data||[]}
function ensureControls(){const card=document.querySelector('[data-view="customers"] .customer-list-card');if(!card)return;const search=card.querySelector('.inline-search');if(!document.getElementById('customerDebtOverview')&&search)search.insertAdjacentHTML('afterend','<div id="customerDebtOverview" class="customer-debt-overview"><div class="legacy-debt-total"><span>Total a receber</span><strong id="customerDebtTotal">R$ 0,00</strong><small id="customerDebtCount">0 fichas em aberto</small></div><label>Ordenar<select id="customerDebtSort"><option value="az">Nome A–Z</option><option value="debt_desc">Maior débito</option><option value="debt_asc">Menor débito</option></select></label><label>Débito mínimo<input id="customerDebtMin" type="number" min="0" step="0.01" placeholder="R$ 0,00"></label></div>')}
function signature(){const list=document.getElementById('customerList');if(!list)return'';return[...list.querySelectorAll('.customer-row')].map(r=>`${r.dataset.customerId}:${r.hidden?'1':'0'}`).join('|')}
async function apply(){if(applying)return;const list=document.getElementById('customerList');if(!list)return;applying=true;try{ensureControls();const cs=await customers(),map=new Map(cs.map(c=>[String(c.id),c]));const total=cs.reduce((s,c)=>s+Math.max(0,Number(c.current_debt||0)),0),count=cs.filter(c=>Number(c.current_debt||0)>0).length;if(document.getElementById('customerDebtTotal'))document.getElementById('customerDebtTotal').textContent=money(total);if(document.getElementById('customerDebtCount'))document.getElementById('customerDebtCount').textContent=`${count} ${count===1?'ficha em aberto':'fichas em aberto'}`;const sort=document.getElementById('customerDebtSort')?.value||'az',min=Math.max(0,Number(document.getElementById('customerDebtMin')?.value||0));let rows=[...list.querySelectorAll('.customer-row')];rows.forEach(r=>{const c=map.get(String(r.dataset.customerId));if(!c)return;const debt=Number(c.current_debt||0),b=r.querySelector(':scope > b');r.dataset.realDebt=String(debt);r.dataset.realName=String(c.customer_name||'');if(b){b.textContent=money(debt);b.dataset.label='Débito atual'}r.hidden=min>0&&debt<min});const visible=rows.filter(r=>!r.hidden);visible.sort((a,b)=>{const da=Number(a.dataset.realDebt||0),dbb=Number(b.dataset.realDebt||0),na=a.dataset.realName||'',nb=b.dataset.realName||'';if(sort==='debt_desc')return dbb-da||na.localeCompare(nb,'pt-BR');if(sort==='debt_asc')return da-dbb||na.localeCompare(nb,'pt-BR');return na.localeCompare(nb,'pt-BR')});const current=visible.map(r=>r.dataset.customerId).join('|'),wanted=[...visible].map(r=>r.dataset.customerId).join('|');if(current!==wanted)visible.forEach(r=>list.appendChild(r));lastSignature=signature()}finally{applying=false}}
function schedule(delay=180){if(applying)return;clearTimeout(timer);timer=setTimeout(()=>apply().catch(console.warn),delay)}
document.addEventListener('change',e=>{if(e.target?.id==='customerDebtSort')schedule(20)});document.addEventListener('input',e=>{if(e.target?.id==='customerDebtMin')schedule(40)});document.addEventListener('click',e=>{if(e.target?.id==='saveCreditEntry'||e.target?.closest('[data-receive-payment]'))setTimeout(()=>schedule(20),500)});
window.addEventListener('load',()=>{const list=document.getElementById('customerList');if(list)new MutationObserver(()=>{if(applying)return;const now=signature();if(now===lastSignature)return;schedule(180)}).observe(list,{childList:true});schedule(50)});
})();