(() => {
'use strict';
let client=null;
const cfg=()=>window.TEM_AQUI_SUPABASE||{};
const configured=()=>Boolean(cfg().url&&(cfg().publishableKey||cfg().anonKey));
const CACHE_TTL={categories:300000,products:120000};
const cache={categories:new Map(),products:new Map()};
const inflight={categories:new Map(),products:new Map()};
const cacheGet=(type,key)=>{const hit=cache[type].get(String(key));return hit&&Date.now()-hit.at<CACHE_TTL[type]?hit.value:null;};
const cacheSet=(type,key,value)=>{cache[type].set(String(key),{at:Date.now(),value});return value;};
function invalidateStore(storeId,{categories=true,products=true}={}){const key=String(storeId||'');if(categories){cache.categories.delete(key);inflight.categories.delete(key);}if(products){cache.products.delete(key);inflight.products.delete(key);}}
function init(){if(!configured()||!window.supabase?.createClient)return false;if(!client)client=window.supabase.createClient(cfg().url,cfg().publishableKey||cfg().anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return true;}
async function q(p){const {data,error}=await p;if(error)throw error;return data;}
async function session(){if(!init())return null;const d=await q(client.auth.getSession());return d?.session||null;}
async function signIn(email,password){if(!init())throw new Error('Banco central não configurado.');const d=await q(client.auth.signInWithPassword({email,password}));return d?.session||null;}
async function signOut(){if(init())await q(client.auth.signOut());cache.categories.clear();cache.products.clear();}
async function roles(uid){if(!uid)return[];try{return [...new Set((await q(client.from('user_roles').select('role').eq('user_id',uid))||[]).map(x=>String(x.role||'').toLowerCase()))];}catch{return[];}}
const perms=r=>({sell:!!r.can_use_pos,products:!!(r.can_manage_products||r.can_add_products||r.can_edit_products),stock:!!r.can_manage_stock,customers:!!r.can_view_customers,credit:!!r.can_view_customers,promotions:!!(r.can_manage_products||r.can_edit_products),reports:!!(r.can_view_reports||r.can_view_revenue),cash:!!(r.can_view_cash||r.can_manage_cash||r.can_open_cash||r.can_close_cash||r.can_move_cash),staff:!!r.can_manage_team,settings:!!(r.can_manage_settings||r.can_manage_hours||r.can_manage_store_images)});
async function myStores(){const s=await session();if(!s?.user)return[];const uid=s.user.id,rr=await roles(uid),out=[];if(rr.some(r=>['admin','administrador'].includes(r))){return (await q(client.from('stores').select('id,name,owner_id,slug,city,whatsapp,logo_url,banner_url,deleted_at').is('deleted_at',null).order('name'))||[]).map(x=>({...x,_role:'owner',_owner:true,_admin:true,_permissions:null}));}const own=await q(client.from('stores').select('id,name,owner_id,slug,city,whatsapp,logo_url,banner_url,deleted_at').eq('owner_id',uid).is('deleted_at',null).order('name'));(own||[]).forEach(x=>out.push({...x,_role:'owner',_owner:true,_permissions:null}));const ms=await q(client.from('store_members').select('store_id,role,status,can_use_pos,can_manage_products,can_add_products,can_edit_products,can_manage_stock,can_view_customers,can_view_reports,can_view_revenue,can_view_cash,can_manage_cash,can_open_cash,can_close_cash,can_move_cash,can_manage_team,can_manage_settings,can_manage_hours,can_manage_store_images').eq('user_id',uid).eq('status','active'));if(ms?.length){const ids=[...new Set(ms.map(x=>x.store_id))],stores=await q(client.from('stores').select('id,name,owner_id,slug,city,whatsapp,logo_url,banner_url,deleted_at').in('id',ids).is('deleted_at',null)),map=new Map(ms.map(x=>[String(x.store_id),x]));(stores||[]).forEach(x=>{if(out.some(y=>y.id===x.id))return;const m=map.get(String(x.id))||{};out.push({...x,_role:String(m.role).toLowerCase()==='manager'?'manager':'editor',_owner:false,_permissions:perms(m)});});}return out.sort((a,b)=>String(a.name).localeCompare(String(b.name),'pt-BR'));}
async function categories(storeId,{force=false}={}){const key=String(storeId);if(!force){const hit=cacheGet('categories',key);if(hit)return hit;if(inflight.categories.has(key))return inflight.categories.get(key);}const task=q(client.from('store_inventory_categories').select('id,name,slug,parent_id,sort_order,active').eq('store_id',storeId).eq('active',true).order('sort_order').order('name')).then(d=>cacheSet('categories',key,d||[])).finally(()=>inflight.categories.delete(key));inflight.categories.set(key,task);return task;}
function mapProduct(p,cat='Outros'){return{id:String(p.id),name:p.name||'Produto',category:cat,categoryId:p.inventory_category_id||null,barcode:p.barcode||'',sku:p.sku||'',price:Number(p.price||0),cost:Number(p.cost_price||0),stock:Number(p.stock??p.stock_quantity??0),minimumStock:Number(p.minimum_stock||0),unit:String(p.unit||'un').replace(/^un$/,'un.'),showcase:p.available!==false,active:p.is_active!==false,image:p.image_url||(Array.isArray(p.images)?p.images[0]:'')||''};}
async function products(storeId,{force=false}={}){const key=String(storeId);if(!force){const hit=cacheGet('products',key);if(hit)return hit;if(inflight.products.has(key))return inflight.products.get(key);}const task=(async()=>{const cc=await categories(storeId),cm=new Map(cc.map(c=>[String(c.id),c.name]));const pageSize=500,rows=[];for(let from=0;;from+=pageSize){const part=await q(client.from('products').select('id,inventory_category_id,name,price,cost_price,stock,stock_quantity,minimum_stock,unit,available,is_active,image_url,images,barcode,sku').eq('store_id',storeId).order('name').range(from,from+pageSize-1));rows.push(...(part||[]));if(!part||part.length<pageSize)break;}return cacheSet('products',key,rows.map(p=>mapProduct(p,cm.get(String(p.inventory_category_id))||'Outros')));})().finally(()=>inflight.products.delete(key));inflight.products.set(key,task);return task;}
const slug=s=>String(s||'categoria').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'categoria';
async function ensureCategory(storeId,name){let d=await q(client.from('store_inventory_categories').select('id,name,slug').eq('store_id',storeId).ilike('name',name).limit(1));if(d?.[0])return d[0];const created=await q(client.from('store_inventory_categories').insert({store_id:storeId,name,slug:slug(name),active:true}).select('id,name,slug').single());invalidateStore(storeId,{categories:true,products:false});return created;}
async function createCategory(storeId,name){const r=await ensureCategory(storeId,name);invalidateStore(storeId);return r;}
async function renameCategory(storeId,oldName,name){const rows=await q(client.from('store_inventory_categories').select('id').eq('store_id',storeId).eq('name',oldName).limit(1));const r=!rows?.[0]?await ensureCategory(storeId,name):await q(client.from('store_inventory_categories').update({name,slug:slug(name),updated_at:new Date().toISOString()}).eq('id',rows[0].id).eq('store_id',storeId).select('id,name').single());invalidateStore(storeId);return r;}
async function saveProduct(storeId,p){const cat=await ensureCategory(storeId,p.category||'Outros');const id=await q(client.rpc('gestao_save_product',{p_store_id:storeId,p_product_id:p.id&&/^[0-9a-f-]{36}$/i.test(String(p.id))?p.id:null,p_name:String(p.name||'').trim(),p_inventory_category_id:cat.id,p_barcode:p.barcode||null,p_sku:p.sku||null,p_price:Math.max(0,Number(p.price||0)),p_cost_price:Math.max(0,Number(p.cost||0)),p_stock:Math.max(0,Number(p.stock||0)),p_minimum_stock:Math.max(0,Number(p.minimumStock||0)),p_unit:String(p.unit||'un.').replace(/^un\.$/,'un'),p_available:p.showcase!==false,p_is_active:p.active!==false,p_image_url:p.image||null}));const fresh=await q(client.from('products').select('id,inventory_category_id,name,price,cost_price,stock,stock_quantity,minimum_stock,unit,available,is_active,image_url,images,barcode,sku').eq('id',id).eq('store_id',storeId).single());invalidateStore(storeId,{categories:false,products:true});return mapProduct(fresh,cat.name);}
async function adjustStock(productId,quantity,type='adjustment',note=''){const value=Number(await q(client.rpc('gestao_adjust_product_stock',{p_product_id:productId,p_quantity:Number(quantity),p_movement_type:type,p_note:note||null})));cache.products.clear();return value;}
async function inventory(storeId,limit=300){return await q(client.from('inventory_movements').select('id,product_id,user_id,movement_type,quantity,previous_stock,new_stock,note,created_at,products(name)').eq('store_id',storeId).order('created_at',{ascending:false}).limit(Math.min(Number(limit)||300,500)))||[];}
async function members(storeId){return await q(client.rpc('gestao_list_store_members',{p_store_id:storeId}))||[];}
async function saveMember(storeId,m){return await q(client.rpc('gestao_upsert_store_member',{p_store_id:storeId,p_email:m.email,p_member_role:m.role,p_permissions:m.permissions||{},p_active:m.active!==false,p_display_name:m.name||''}));}
async function setMemberActive(storeId,userId,active){return await q(client.rpc('gestao_set_store_member_active',{p_store_id:storeId,p_user_id:userId,p_active:!!active}));}
async function customers(storeId,search=''){return await q(client.rpc('gestao_list_customers',{p_store_id:storeId,p_search:search||null}))||[];}
async function saveCustomer(storeId,c){return await q(client.rpc('gestao_upsert_customer',{p_store_id:storeId,p_customer_id:c.id||null,p_name:c.name,p_whatsapp:c.whatsapp||null,p_credit_limit:Number(c.limit||0),p_notes:c.notes||null}));}
async function customerCredit(storeId,customerId){return await q(client.rpc('gestao_list_customer_credit',{p_store_id:storeId,p_customer_id:customerId}))||[];}
async function receivePayment(storeId,customerId,amount,note=''){return Number(await q(client.rpc('gestao_receive_customer_payment',{p_store_id:storeId,p_customer_id:customerId,p_amount:Number(amount),p_note:note||null})));}
async function openCash(storeId,opening=0,note=''){return await q(client.rpc('open_pos_cash',{p_store_id:storeId,p_opening_amount:Number(opening),p_notes:note||null}));}
async function openCashInfo(storeId){const d=await q(client.rpc('get_my_open_pos_cash',{p_store_id:storeId}));return d?.[0]||null;}
async function closeCash(cashId,counted,note=''){return await q(client.rpc('close_store_cash_v1012',{p_cash_session_id:cashId,p_counted_amount:Number(counted),p_notes:note||null}));}
async function cashReport(storeId,start,end){return await q(client.rpc('get_store_cash_report',{p_store_id:storeId,p_start:start||new Date(Date.now()-30*86400000).toISOString(),p_end:end||new Date(Date.now()+86400000).toISOString()}))||[];}
async function finalizeSale(storeId,data){const items=(data.items||[]).map(i=>({productId:i.productId||null,name:i.name||'Item',unit:String(i.unit||'un.').replace(/^un\.$/,'un'),qty:Number(i.qty||0),price:Number(i.price||0)}));const r=await q(client.rpc('gestao_finalize_sale',{p_store_id:storeId,p_items:items,p_payment_method:data.payment,p_discount:Number(data.discount||0),p_surcharge:Number(data.surcharge||0),p_amount_received:data.cashReceived==null?null:Number(data.cashReceived),p_customer_id:data.customerId||null,p_due_date:data.dueDate||null,p_note:data.note||null}));invalidateStore(storeId,{categories:false,products:true});return r;}
async function sales(storeId,limit=500){return await q(client.rpc('gestao_list_sales',{p_store_id:storeId,p_limit:Math.min(Number(limit)||500,1000)}))||[];}
async function saleItems(saleId){return await q(client.rpc('gestao_list_sale_items',{p_sale_id:saleId}))||[];}
async function promotions(storeId){return await q(client.rpc('gestao_list_promotions',{p_store_id:storeId}))||[];}
async function savePromotion(storeId,p){return await q(client.rpc('gestao_save_promotion',{p_store_id:storeId,p_campaign_key:p.id||null,p_title:p.name,p_discount_percent:Number(p.discountPercent),p_starts_at:p.startAt,p_ends_at:p.endAt,p_product_ids:p.productIds,p_publish:!!p.publish,p_active:p.active!==false}));}
async function setPromotionActive(storeId,id,active){return await q(client.rpc('gestao_set_promotion_active',{p_store_id:storeId,p_campaign_key:id,p_active:!!active}));}
async function context(preferred=''){const s=await session();if(!s?.user)return{session:null,stores:[],store:null};const ss=await myStores(),store=ss.find(x=>String(x.id)===String(preferred))||ss[0]||null;if(!store)return{session:s,stores:ss,store:null};return{session:s,stores:ss,store,membership:{isOwner:!!store._owner,isAdmin:!!store._admin,role:store._role||'editor',permissions:store._owner||store._admin?null:(store._permissions||{})}};}
window.GestaoBackend={init,isConfigured:configured,getSession:session,signIn,signOut,myStores,categories,products,createCategory,renameCategory,saveProduct,adjustStock,inventory,members,saveMember,setMemberActive,customers,saveCustomer,customerCredit,receivePayment,openCash,openCashInfo,closeCash,cashReport,finalizeSale,sales,saleItems,promotions,savePromotion,setPromotionActive,context,invalidateStore};
})();