(() => {
'use strict';
const B0=window.GestaoBackend,S=window.GestaoOfflineStore;if(!B0||!S)return;
const ctxKey='device-context';let syncing=false;
const netErr=e=>!navigator.onLine||/failed to fetch|network|timeout|offline|connection|402|429|500|502|503|504|quota|rate limit|limit exceeded|exceeded|billing|egress|project paused|project is paused|temporarily unavailable|service unavailable/i.test(String(e?.message||e||''));
const totalSale=d=>Math.max(0,(d.items||[]).reduce((a,i)=>a+Number(i.qty||0)*Number(i.price||0),0)-Number(d.discount||0)+Number(d.surcharge||0));
async function saveCtx(c){if(c?.store)await S.put('meta',{key:ctxKey,value:{stores:c.stores||[],store:c.store,membership:c.membership||null,userId:c.session?.user?.id||null}});}
async function getCtx(){return S.get('meta',ctxKey);}
async function read(name,type,storeId,args,fallback){if(navigator.onLine){try{const v=await B0[name](...args);await S.save(type,storeId,v);return v;}catch(e){if(!netErr(e))throw e;}}return S.load(type,storeId,fallback);}
async function refresh(storeId){if(!navigator.onLine||!storeId)return;const jobs=[['products',()=>B0.products(storeId,{force:true})],['categories',()=>B0.categories(storeId,{force:true})],['customers',()=>B0.customers(storeId)],['sales',()=>B0.sales(storeId,1000)],['promotions',()=>B0.promotions(storeId)],['cash',()=>B0.openCashInfo(storeId)],['inventory',()=>B0.inventory(storeId,300)],['staff',()=>B0.members(storeId)]];await Promise.all(jobs.map(async([t,f])=>{try{await S.save(t,storeId,await f());}catch{}}));}
async function localSale(storeId,d,qid){const pp=await S.load('products',storeId,[]);for(const i of d.items||[]){if(!i.productId)continue;const p=pp.find(x=>String(x.id)===String(i.productId));if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(i.qty||0));}await S.save('products',storeId,pp);const ss=await S.load('sales',storeId,[]);const row={id:`offline-${qid}`,created_at:new Date().toISOString(),total:totalSale(d),item_count:(d.items||[]).length,status:'pending_sync',payment_detail:d.payment,payment_method:d.payment,customer_id:d.customerId||null,offline:true};ss.unshift(row);await S.save('sales',storeId,ss.slice(0,1500));if(d.payment==='ficha'&&d.customerId){const cc=await S.load('customers',storeId,[]),c=cc.find(x=>String(x.id)===String(d.customerId));if(c){c.current_debt=Number(c.current_debt||0)+row.total;c.total_spent=Number(c.total_spent||0)+row.total;c.last_purchase=row.created_at;await S.save('customers',storeId,cc);}}return row.id;}
async function sync(){if(syncing||!navigator.onLine)return;syncing=true;try{for(const q of await S.pending()){try{await B0[q.op](...(q.args||[]));await S.del('queue',q.id);}catch(e){q.attempts=Number(q.attempts||0)+1;q.lastError=String(e?.message||e);await S.put('queue',q);break;}}const c=await getCtx();if(c?.store?.id)await refresh(c.store.id);}finally{syncing=false;badge();}}
async function badge(){let e=document.getElementById('offlineSyncBadge');if(!e){e=document.createElement('button');e.id='offlineSyncBadge';e.type='button';Object.assign(e.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'99999',border:'0',borderRadius:'999px',padding:'9px 13px',fontWeight:'700',fontSize:'12px',boxShadow:'0 4px 18px rgba(0,0,0,.22)',cursor:'pointer'});e.onclick=async()=>{if(navigator.onLine){e.textContent='Sincronizando…';await sync();location.reload();}};document.body.appendChild(e);}const n=(await S.pending()).length;e.textContent=navigator.onLine?(n?`🟡 Online · ${n} pendência${n===1?'':'s'}`:'🟢 Online · sincronizado'):`🔴 Offline · ${n} pendência${n===1?'':'s'}`;e.style.background=navigator.onLine?(n?'#f59e0b':'#0b7a3d'):'#b91c1c';e.style.color='#fff';}
const B={...B0};
B.context=async preferred=>{try{const c=await B0.context(preferred);await saveCtx(c);return c;}catch(e){if(!netErr(e))throw e;const c=await getCtx();if(!c?.store)return{session:null,stores:[],store:null};let session=null;try{session=await B0.getSession();}catch{}if(!session)session={user:{id:c.userId||'offline-device'},offline:true};const store=(c.stores||[]).find(x=>String(x.id)===String(preferred))||c.store;return{session,stores:c.stores||[store],store,membership:c.membership,offline:true};}};
B.products=(id,o={})=>read('products','products',id,[id,o],[]);B.categories=(id,o={})=>read('categories','categories',id,[id,o],[]);B.customers=(id,s='')=>read('customers','customers',id,[id,s],[]);B.sales=(id,l=500)=>read('sales','sales',id,[id,l],[]);B.promotions=id=>read('promotions','promotions',id,[id],[]);B.openCashInfo=id=>read('openCashInfo','cash',id,[id],null);B.inventory=(id,l=300)=>read('inventory','inventory',id,[id,l],[]);B.members=id=>read('members','staff',id,[id],[]);
B.finalizeSale=async(id,d)=>{try{const r=await B0.finalizeSale(id,d);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const q=await S.enqueue('finalizeSale',id,[id,d]);await badge();return localSale(id,d,q);}};
B.adjustStock=async(pid,q,t='adjustment',n='')=>{try{const r=await B0.adjustStock(pid,q,t,n);const c=await getCtx();if(c?.store?.id)await refresh(c.store.id);return r;}catch(e){if(!netErr(e))throw e;const c=await getCtx(),id=c?.store?.id,pp=await S.load('products',id,[]),p=pp.find(x=>String(x.id)===String(pid));if(p){p.stock=Math.max(0,Number(p.stock||0)+Number(q||0));await S.save('products',id,pp);}await S.enqueue('adjustStock',id,[pid,q,t,n]);await badge();return p?.stock||0;}};
B.saveProduct=async(id,p)=>{try{const r=await B0.saveProduct(id,p);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const pp=await S.load('products',id,[]),localId=p.id||`offline-product-${crypto.randomUUID()}`,row={...p,id:localId,stock:Number(p.stock||0),price:Number(p.price||0),cost:Number(p.cost||0),minimumStock:Number(p.minimumStock||0)};const x=pp.findIndex(v=>String(v.id)===String(localId));if(x>=0)pp[x]={...pp[x],...row};else pp.unshift(row);await S.save('products',id,pp);await S.enqueue('saveProduct',id,[id,{...p,id:p.id&&String(p.id).startsWith('offline-product-')?null:p.id}]);await badge();return row;}};
B.saveCustomer=async(id,c)=>{try{const r=await B0.saveCustomer(id,c);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const rows=await S.load('customers',id,[]),localId=c.id||`offline-customer-${crypto.randomUUID()}`,row={id:localId,customer_name:c.name,whatsapp:c.whatsapp||'',credit_limit:Number(c.limit||0),current_debt:Number(c.debt||0),total_spent:Number(c.totalSpent||0),notes:c.notes||''},x=rows.findIndex(v=>String(v.id)===String(localId));if(x>=0)rows[x]={...rows[x],...row};else rows.unshift(row);await S.save('customers',id,rows);await S.enqueue('saveCustomer',id,[id,{...c,id:c.id&&String(c.id).startsWith('offline-customer-')?null:c.id}]);await badge();return localId;}};
B.receivePayment=async(id,cid,a,n='')=>{try{const r=await B0.receivePayment(id,cid,a,n);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const rows=await S.load('customers',id,[]),c=rows.find(x=>String(x.id)===String(cid));if(c)c.current_debt=Math.max(0,Number(c.current_debt||0)-Number(a||0));await S.save('customers',id,rows);await S.enqueue('receivePayment',id,[id,cid,a,n]);await badge();return c?.current_debt||0;}};
B.createCategory=async(id,n)=>{try{const r=await B0.createCategory(id,n);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const rows=await S.load('categories',id,[]),row={id:`offline-category-${crypto.randomUUID()}`,name:n,active:true};rows.push(row);await S.save('categories',id,rows);await S.enqueue('createCategory',id,[id,n]);await badge();return row;}};
B.renameCategory=async(id,a,n)=>{try{const r=await B0.renameCategory(id,a,n);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;const rows=await S.load('categories',id,[]),c=rows.find(x=>x.name===a);if(c)c.name=n;await S.save('categories',id,rows);const pp=await S.load('products',id,[]);pp.forEach(p=>{if(p.category===a)p.category=n;});await S.save('products',id,pp);await S.enqueue('renameCategory',id,[id,a,n]);await badge();return c||{name:n};}};
B.openCash=async(id,o=0,n='')=>{try{const r=await B0.openCash(id,o,n);await S.save('cash',id,r);return r;}catch(e){if(!netErr(e))throw e;const r={id:`offline-cash-${crypto.randomUUID()}`,store_id:id,opening_amount:Number(o||0),opened_at:new Date().toISOString(),status:'open',offline:true};await S.save('cash',id,r);await S.enqueue('openCash',id,[id,o,n]);await badge();return r;}};
B.closeCash=async(cid,c,n='')=>{try{return await B0.closeCash(cid,c,n);}catch(e){if(!netErr(e))throw e;const x=await getCtx();if(x?.store?.id)await S.save('cash',x.store.id,null);await S.enqueue('closeCash',x?.store?.id,[cid,c,n]);await badge();return true;}};
B.savePromotion=async(id,p)=>{try{const r=await B0.savePromotion(id,p);await refresh(id);return r;}catch(e){if(!netErr(e))throw e;await S.enqueue('savePromotion',id,[id,p]);await badge();return p.id||`offline-promo-${crypto.randomUUID()}`;}};
B.setPromotionActive=async(id,pid,a)=>{try{return await B0.setPromotionActive(id,pid,a);}catch(e){if(!netErr(e))throw e;await S.enqueue('setPromotionActive',id,[id,pid,a]);await badge();return true;}};
B.syncOfflineQueue=sync;window.GestaoBackend=B;window.GestaoOffline={sync,refresh};
window.addEventListener('online',()=>setTimeout(sync,1000));window.addEventListener('offline',badge);window.addEventListener('load',()=>{badge();if(navigator.onLine)setTimeout(sync,2500);});setInterval(()=>{if(navigator.onLine)sync();},30000);
})();
