(() => {
'use strict';
let client=null,rows=[],categories=[],visible=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const cfg=()=>window.TEM_AQUI_SUPABASE||{};
const storeId=()=>localStorage.getItem('tag-pref-store')||'';
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function ensureClient(){if(client)return client;const c=cfg();if(!window.supabase?.createClient||!c.url||!(c.publishableKey||c.anonKey))return null;client=window.supabase.createClient(c.url,c.publishableKey||c.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client;}
function ensureUi(){const view=document.querySelector('.view[data-view="products"]');if(!view||$('storefrontSyncCard'))return;const anchor=view.querySelector('.product-category-panel')||view.querySelector('.management-grid');if(!anchor)return;const card=document.createElement('section');card.id='storefrontSyncCard';card.className='storefront-sync-card';card.innerHTML=`<div class="storefront-sync-head"><div><h2>🛍 Vitrine Tem Aqui</h2><p>Escolha quais produtos desta loja aparecem para os clientes no Tem Aqui. O produto pode continuar no estoque e no PDV mesmo fora da vitrine.</p></div><div class="storefront-sync-actions"><button type="button" id="storefrontRefreshButton" class="storefront-refresh-btn">↻ Atualizar</button><button type="button" id="storefrontManageButton" class="storefront-manage-btn">Gerenciar vitrine</button></div></div><div class="storefront-sync-stats"><div><span>Total da loja</span><strong id="storefrontTotal">—</strong></div><div><span>No Tem Aqui</span><strong id="storefrontPublished">—</strong></div><div><span>Só no Gestão</span><strong id="storefrontHidden">—</strong></div></div>`;anchor.parentNode.insertBefore(card,anchor);
const dialog=document.createElement('dialog');dialog.id='storefrontDialog';dialog.className='storefront-dialog';dialog.innerHTML=`<form method="dialog"><header><h2>Produtos na vitrine do Tem Aqui</h2><p>Marque os produtos e publique ou retire da vitrine em um único comando.</p></header><div class="storefront-toolbar"><input id="storefrontSearch" placeholder="Buscar produto, código ou SKU"><select id="storefrontCategory"><option value="">Todas as categorias</option></select><select id="storefrontStatus"><option value="all">Todos</option><option value="on">Publicados</option><option value="off">Fora da vitrine</option></select></div><div id="storefrontProductList" class="storefront-product-list"></div><div class="storefront-footer"><div class="storefront-footer-left"><button type="button" id="storefrontSelectVisible" class="storefront-select-visible">Selecionar visíveis</button><button type="button" id="storefrontClearSelection" class="storefront-select-visible">Limpar seleção</button></div><div class="storefront-footer-right"><button type="button" id="storefrontHideSelected" class="storefront-hide">Retirar do Tem Aqui</button><button type="button" id="storefrontPublishSelected" class="storefront-publish">Publicar no Tem Aqui</button><button type="button" id="storefrontClose" class="storefront-close">Fechar</button></div></div></form>`;document.body.appendChild(dialog);
$('storefrontManageButton').addEventListener('click',openManager);$('storefrontRefreshButton').addEventListener('click',loadData);$('storefrontClose').addEventListener('click',()=>dialog.close());$('storefrontSearch').addEventListener('input',renderList);$('storefrontCategory').addEventListener('change',renderList);$('storefrontStatus').addEventListener('change',renderList);$('storefrontSelectVisible').addEventListener('click',()=>{visible.forEach(r=>{const x=document.querySelector(`[data-storefront-check="${r.id}"]`);if(x)x.checked=true;});});$('storefrontClearSelection').addEventListener('click',()=>document.querySelectorAll('[data-storefront-check]').forEach(x=>x.checked=false));$('storefrontPublishSelected').addEventListener('click',()=>applySelected(true));$('storefrontHideSelected').addEventListener('click',()=>applySelected(false));loadData();}
async function loadData(){const c=ensureClient(),sid=storeId();if(!c||!sid)return;try{const [pr,cr]=await Promise.all([c.from('products').select('id,name,available,is_active,inventory_category_id,price,image_url,images,barcode,sku').eq('store_id',sid).order('name').limit(10000),c.from('store_inventory_categories').select('id,name').eq('store_id',sid).eq('active',true).order('name')]);if(pr.error)throw pr.error;if(cr.error)throw cr.error;rows=pr.data||[];categories=cr.data||[];updateStats();renderCategory();renderList();decorateRows();}catch(e){console.warn('Vitrine Tem Aqui:',e);}}
function updateStats(){if(!$('storefrontTotal'))return;$('storefrontTotal').textContent=rows.length;$('storefrontPublished').textContent=rows.filter(r=>r.available!==false&&r.is_active!==false).length;$('storefrontHidden').textContent=rows.filter(r=>r.available===false).length;}
function renderCategory(){const s=$('storefrontCategory');if(!s)return;const v=s.value;s.innerHTML='<option value="">Todas as categorias</option>'+categories.map(c=>`<option value="${c.id}" ${String(c.id)===String(v)?'selected':''}>${esc(c.name)}</option>`).join('');}
function categoryName(id){return categories.find(c=>String(c.id)===String(id))?.name||'Sem categoria';}
function imageOf(r){return r.image_url||(Array.isArray(r.images)?r.images[0]:'')||'';}
function filtered(){const term=String($('storefrontSearch')?.value||'').toLowerCase().trim(),cat=$('storefrontCategory')?.value||'',status=$('storefrontStatus')?.value||'all';return rows.filter(r=>(!term||`${r.name} ${r.barcode||''} ${r.sku||''}`.toLowerCase().includes(term))&&(!cat||String(r.inventory_category_id)===String(cat))&&(status==='all'||(status==='on'?(r.available!==false&&r.is_active!==false):r.available===false)));}
function renderList(){const host=$('storefrontProductList');if(!host)return;visible=filtered();host.innerHTML=visible.map(r=>{const img=imageOf(r),on=r.available!==false&&r.is_active!==false;return `<label class="storefront-row"><input type="checkbox" data-storefront-check="${r.id}">${img?`<img src="${esc(img)}" alt="">`:'<span class="storefront-thumb">📦</span>'}<span><b>${esc(r.name)}</b><small>${esc(categoryName(r.inventory_category_id))} · ${money(r.price)}${r.barcode?` · ${esc(r.barcode)}`:''}</small></span><span class="storefront-status ${on?'on':'off'}">${on?'No Tem Aqui':'Só Gestão'}</span></label>`;}).join('')||'<div class="storefront-empty">Nenhum produto encontrado com esse filtro.</div>';}
async function openManager(){await loadData();$('storefrontDialog')?.showModal();}
async function applySelected(available){const ids=[...document.querySelectorAll('[data-storefront-check]:checked')].map(x=>x.dataset.storefrontCheck);if(!ids.length)return alert('Selecione pelo menos um produto.');const c=ensureClient(),sid=storeId();try{const {data,error}=await c.rpc('gestao_set_products_storefront',{p_store_id:sid,p_product_ids:ids,p_available:available});if(error)throw error;await loadData();alert(`${Number(data||ids.length)} produto(s) ${available?'publicado(s) no':'retirado(s) do'} Tem Aqui.`);}catch(e){alert(e.message||String(e));}}
function decorateRows(){document.querySelectorAll('[data-edit-product]').forEach(el=>{const p=rows.find(r=>String(r.id)===String(el.dataset.editProduct));if(p)el.dataset.showcase=String(p.available!==false&&p.is_active!==false);});}
const observer=new MutationObserver(()=>{ensureUi();decorateRows();});
function start(){ensureUi();observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('focus',()=>loadData());}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();